name: Docker CI for Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-docker-image:${{ github.sha }} .

      - name: Run Docker container
        run: |
          docker run --name my-container -d my-docker-image:${{ github.sha }}

      - name: Run Tests
        run: |
          docker exec my-container mvn test

      - name: Stop and remove the Docker container
        run: |
          docker stop my-container
          docker rm my-container

      - name: Remove Docker image
        run: |
          docker rmi my-docker-image:${{ github.sha }}
